version: ‘3’
services:
  my-sql-server:
  container_name: prince-mysql
  image: mysql:latest
  ports:
  - "3306:3306"

java-crud-app:
  container_name: prince-spring-boot
  image: spring-boot-sudent
  ports:
   8080:8080
  environment:
  - DATABASE_URL=jdbc:mysql://prince-mysql:3306/dockeremployee
  - DATABASE_USERNAME=username
  - DATABASE_PASSWORD=root
  depends_on:
  - my-sql-server