services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dockeremployee
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - spring-boot-prince
  spring-boot-app:
    container_name: spring-demo
    image: spring-boot-prince
    ports:
      - "8080:8080"
    networks:
      - spring-boot-prince
    depends_on:
      - postgres
volumes:
  postgres:

networks:
  spring-boot-prince:
    driver: bridge
